### ISSUE TITLE
Does not work in Ubuntu 22.04

### ISSUE THREAD

**Issue by lisavani** [GoBig87/NordVpnLinuxGUI#7]
Hi, installing your GUI in Ubuntu 22.04 results in an error:

"ERROR: Could not build wheels for Kivy, which is required to install pyproject.toml-based projects"

I hope you can fix this, because it was very nice working in previous Ubuntu versions.

Kind regards, Lisa

**Comment by GoBig87** [comment]
I think this is because Ubuntu 22.04 comes with python 3.10 as the default python3 version.  Kivy 2.1.0 is supposed to support python 3.10 and I've updated the requirements.txt from kivy 2.0.0 -> 2.1.0.  Hopefully thats the issue and it solves it for you.  
https://github.com/GoBig87/NordVpnLinuxGUI/commit/f6485e38a4d4cf199a3704291d77516c2898e49b

**Comment by lisavani** [comment]
Thank you for the quick response! The Kivy problem is now resolved but a new problem came in its place:

Creating desktop Icon
/home/lisa/NordVpnLinuxGUI-main/NordVPN.desktop
cp: cannot create regular file '/root/Desktop/NordVPN.desktop': No such file or directory
chown: cannot access '/root/Desktop/NordVPN.desktop': No such file or directory
Finished Installation
To Enable desktop launching, right click on the NordVON.desktop cog Icon and right click and select 'Allow Launching'

No desktop icon and no way to continue. I hope you have the time and spirit to fix this too?

Greetings, Lisa

**Comment by GoBig87** [comment]
I'm not sure why your ~/ was giving you /root but I switched to the full path name for the installer.

https://github.com/GoBig87/NordVpnLinuxGUI/commit/9dc065f46178efeecea4c626291bac9c283d2318

**Comment by DIW79** [comment]
I had the same problem with the desktop icon - none was made. I just installed ubuntu and the GUI this afternoon. I have also opened another issue as login seems not to be working. I have left extensive output for you there, I sincerely hope it helps because this is an exceedingly worthy project.

Thank you for your hard work and dedication!

**Comment by DIW79** [comment]
> I'm not sure why your ~/ was giving you /root but I switched to the full path name for the installer.
> 
> [9dc065f](https://github.com/GoBig87/NordVpnLinuxGUI/commit/9dc065f46178efeecea4c626291bac9c283d2318)

I had the same problem with the desktop icon - none was made. I just installed ubuntu and the GUI this afternoon. I have also opened another issue as login seems not to be working. I have left extensive output for you there, I sincerely hope it helps because this is an exceedingly worthy project.

Thank you for your hard work and dedication!

**Comment by dim6003** [comment]
Hello, same problem here, Desktop icon is not created...
because I don't have a "Desktop" folder, but a french installation "Bureau" folder instead !
I don't know how to find the translated names of ~ standard folders, just did a quick search, without success.

**Comment by ZachAR3** [comment]
> Hello, same problem here, Desktop icon is not created... because I don't have a "Desktop" folder, but a french installation "Bureau" folder instead ! I don't know how to find the translated names of ~ standard folders, just did a quick search, without success.
> 
> Edit : I copied and launched in a terminal modified lines 69 and 70 from installer.sh :
> 
> ```
> sudo cp /usr/share/applications/NordVPN.desktop /home/$USER/Bureau/NordVPN.desktop
> sudo chown $USER /home/$USER/Bureau/NordVPN.desktop
> ```
> 
> And pb solved on my side. But I guess many other non-english users may encounter the same issue.

Fixed using `"$(xdg-user-dir DESKTOP)/NordVPN.desktop"` which should give the desktop regardless of language.
